ci: adding sqlite file and adding migration on the container; adding password coming from env

diff --git a/docker/8.4/start-container b/docker/8.4/start-container
--- a/docker/8.4/start-container
+++ b/docker/8.4/start-container
@@ -9,6 +9,10 @@ if [ -n "${PORT}" ]; then
     export SUPERVISOR_PHP_COMMAND="/usr/bin/php8.4 -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=${PORT}"
 fi
 
+if [ -f /var/www/html/artisan ]; then
+    php /var/www/html/artisan migrate --force --no-interaction || echo "Database migration failed (continuing)"
+fi
+
 if [ ! -z "$WWWUSER" ]; then
     usermod -u $WWWUSER sail
 fi
